# Generated content
# SPDX-License-Identifier: CC-BY-4.0
# SPDX-FileCopyrightText: Copyright Â© metaeffekt GmbH 2022. All rights reserved.

canonicalName: "Zendesk Application Developer and API Agreement 2022"
category: "Zendesk"
shortName: "Zendesk-AppDev-API-2022"

otherIds: 
  - "scancode:zendesk-appdev-api-2022"
