# Generated content
# SPDX-License-Identifier: CC-BY-4.0
# SPDX-FileCopyrightText: Copyright Â© metaeffekt GmbH 2022. All rights reserved.

canonicalName: "AddThis Mobile Application SDK License 1.0"
category: "AddThis Mobile Application SDK License"
shortName: "AddThis-Mobile-SDK-1.0"

alternativeNames:
  - "ADDTHIS MOBILE APPLICATION SDK LICENSE AGREEMENT"
  - "http://www.addthis.com/tos"

otherIds: 
  - "scancode:addthis-mobile-sdk-1.0"
