[versions]
ort = "31.0.0"

[libraries]
ortEvaluator = { module = "org.ossreviewtoolkit:evaluator", version.ref = "ort" }
ortNotifier = { module = "org.ossreviewtoolkit:notifier", version.ref = "ort" }
ortReporter = { module = "org.ossreviewtoolkit:reporter", version.ref = "ort" }

[bundles]
ortScriptDefinitions = [
    "ortEvaluator",  # Contains the script definition for "*.rules.kts" files.
    "ortNotifier",   # Contains the script definition for "*.notifications.kts" files.
    "ortReporter"    # Contains the script definition for "*.how-to-fix-text-provider.kts" files.
]
