- id: "NuGet::AWSSDK.ApplicationInsights:[3.3.538,)"
  curations:
    comment: "Set the VCS path of the module inside the multi-module repository."
    vcs:
      path: "sdk/src/Services/ApplicationInsights"
