- id: "NuGet::AWSSDK.ApplicationAutoScaling.PCL:[3.1.70,)"
  curations:
    comment: "Set the VCS path of the module inside the multi-module repository."
    vcs:
      path: "sdk/src/Services/ApplicationAutoScaling"
