- id: "NuGet::Azure.ResourceManager.DeploymentManager:"
  curations:
    comment: "Set the VCS path of the module inside the multi-module repository."
    vcs:
      path: "sdk/deploymentmanager/Azure.ResourceManager.DeploymentManager"
