- id: "NuGet::Azure.ResourceManager.Automation:"
  curations:
    comment: "Set the VCS path of the module inside the multi-module repository."
    vcs:
      path: "sdk/automation/Azure.ResourceManager.Automation"
