- id: "NuGet::Azure.ResourceManager.GuestConfiguration:"
  curations:
    comment: "Set the VCS path of the module inside the multi-module repository."
    vcs:
      path: "sdk/guestconfiguration/Azure.ResourceManager.GuestConfiguration"
