- id: "NuGet::Microsoft.Extensions.ApplicationModelDetection:[2.1.7,)"
  curations:
    comment: "Set the VCS path of the module inside the multi-module repository."
    vcs:
      path: "src/AzureIntegration/src/Microsoft.Extensions.ApplicationModelDetection"
