- id: "NuGet::Microsoft.AspNetCore.ApplicationInsights.HostingStartup:2.1.7"
  curations:
    comment: "Set the VCS path of the module inside the multi-module repository."
    vcs:
      path: "src/AzureIntegration/src/Microsoft.AspNetCore.ApplicationInsights.HostingStartup"
- id: "NuGet::Microsoft.AspNetCore.ApplicationInsights.HostingStartup:2.2.1"
  curations:
    comment: "Set the VCS path of the module inside the multi-module repository."
    vcs:
      path: "src/AzureIntegration/src/Microsoft.AspNetCore.ApplicationInsights.HostingStartup"
- id: "NuGet::Microsoft.AspNetCore.ApplicationInsights.HostingStartup:[2.1.8,2.1.31]"
  curations:
    comment: "Set the VCS path of the module inside the multi-module repository."
    vcs:
      path: "src/Azure/ApplicationInsights.HostingStartup/src"
- id: "NuGet::Microsoft.AspNetCore.ApplicationInsights.HostingStartup:[2.2.2,)"
  curations:
    comment: "Set the VCS path of the module inside the multi-module repository."
    vcs:
      path: "src/Azure/ApplicationInsights.HostingStartup/src"
