- id: "NuGet::Microsoft.dotnet-openapi:[3.0.0,)"
  curations:
    comment: "Set the VCS path of the module inside the multi-module repository."
    vcs:
      path: "src/Tools/Microsoft.dotnet-openapi/src"
