- id: "NuGet::Microsoft.Azure.Management.GuestConfiguration:"
  curations:
    comment: "Set the VCS path of the module inside the multi-module repository."
    vcs:
      path: "sdk/guestconfiguration/Microsoft.Azure.Management.GuestConfiguration"
