# Generated content
# SPDX-License-Identifier: CC-BY-4.0
# SPDX-FileCopyrightText: Copyright Â© metaeffekt GmbH 2022. All rights reserved.
canonicalName: "Java Application Stub Binary Module License"
category: "Java Application Stub Binary Module License"
shortName: "Java-App-Stub"

alternativeNames:
  - "java-app-stub"

otherIds: 
  - "scancode:java-app-stub"
