[versions]
ort = "55.2.0"

[libraries]
ortModel = { module = "org.ossreviewtoolkit:model", version.ref = "ort" }
ortNuGetPackageManager = { module = "org.ossreviewtoolkit.plugins.packagemanagers:nuget-package-manager", version.ref = "ort" }
