# Generated content
# SPDX-License-Identifier: CC-BY-4.0
# SPDX-FileCopyrightText: Copyright Â© metaeffekt GmbH 2022. All rights reserved.

canonicalName: "Simplified Artistic License (eNetwizard Content Application Server)"
category: "Simplified Artistic License"
shortName: "Simplified Artistic License (eNetwizard Content Application Server)"

osiStatus: "unclear"

