# Generated content
# SPDX-License-Identifier: CC-BY-4.0
# SPDX-FileCopyrightText: Copyright Â© metaeffekt GmbH 2022. All rights reserved.
canonicalName: "IBM Java Runtime Environment License"
category: "IBM Java Runtime Environment License"
shortName: "IBM-JRE"

alternativeNames:
  - "ibm-jre"

otherIds: 
  - "scancode:ibm-jre"
