# Generated content
# SPDX-License-Identifier: CC-BY-4.0
# SPDX-FileCopyrightText: Copyright Â© metaeffekt GmbH 2022. All rights reserved.
canonicalName: "Texas Instruments Broadband Applications License"
category: "Texas Instruments Broadband Applications License"
shortName: "TI-Broadband-Apps"

alternativeNames:
  - "Texas Instruments Broadband Applications License"
  - "ti-broadband-apps"

otherIds: 
  - "scancode:ti-broadband-apps"
