---
# SPDX-FileCopyrightText: 2021 HH Partners, Attorneys-at-law Ltd <doubleopen@hhpartners.fi>
# SPDX-License-Identifier: CC0-1.0

name: Check

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  Check:
    runs-on: ubuntu-latest
    container:
      image: doubleopen/ort:poc-0.1.2

    steps:
      - name: Clone the repository
        uses: actions/checkout@v2
      - name: Check license-classifications.yml
        run: |
          /opt/ort/bin/orth list-license-categories -i license-classifications.yml

  Lint:
    runs-on: ubuntu-latest

    steps:
      - name: Clone the repository
        uses: actions/checkout@v2
      - name: Lint YAML files
        uses: ibiqlik/action-yamllint@v3

  REUSE:
    runs-on: ubuntu-latest

    steps:
      - name: Clone the repository
        uses: actions/checkout@v2
      - name: REUSE Compliance Check
        uses: fsfe/reuse-action@v1
